version: '2.1'

services:
  addressapi:
    image: address
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Host=addressDb;Port=5432;Username=address;Password=@Qualidade2#!;Database=capitalChurch;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - addressDb
    ports:
      - "8082:80"

  addressDb:
    image: mdillon/postgis
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=capitalChurch
      - POSTGRES_USER=address
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"