branch-defaults:
  master:
    environment: Capitalchurchaddress-env-1
environment-defaults:
  Capitalchurchaddress-env-1:
    branch: null
    repository: null
global:
  application_name: Capital.Church.Address
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/Docker running on
    64bit Amazon Linux/2.12.17
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
