version: "3"

services:
  addressDb:
    image: mdillon/postgis
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=capitalChurch
      - POSTGRES_USER=address
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5455:5432"
